language: java
jdk:
  - oraclejdk8
script:
  - mvn test
  
before_script:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git checkout 2.4
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - sudo make -j8 install
  - cd ../..
  - mkdir -p native/linux/x86_64
  - cp opencv/build/lib/libopencv_java248.so native/linux/x86_64/libopencv_java320.so
  - cp opencv/build/bin/opencv-320.jar .
  - jar -cMf opencv-native-320.jar native
  - lein2 localrepo install opencv-248.jar opencv/opencv 3.2.0
  - lein2 localrepo install opencv-native-248.jar opencv/opencv-native 3.2.0

